### ISSUE TITLE
APPEND operation is not mandatory here

### ISSUE THREAD

**Issue by the-bytecode** [maddipatla/Java-Learning-Tasks#16]
https://github.com/maddipatla/Java-Learning-Tasks/blob/040bee0ebe2597f78abdc2ae48fa39398f72997e/Multithreading/src/main/java/com/learningbydoing/splitfilebynlines/WriteThread.java#L58

**Comment by maddipatla** [comment]
used StandardOpenOption.TRUNCATE_EXISTING
